name: dl9
recipe: drupal9
config:
  webroot: web
  xdebug: true
  config:
    php: ./php.ini
proxy:
  appserver:
    - dl9.lndo.site
tooling:
  drupal:
    service: appserver
    cmd: "/app/vendor/bin/drupal --root=/app/web"
  drush:
    cmd: "/app/vendor/bin/drush --root=/app/web"
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "http://dl9.lndo.site"